import type { Metadata } from "next";
// import "./globals.css";
import Footer from "@/components/layout/footer";
// import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "GO Spives",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <Navbar /> */}
      {children}
      <Footer />
    </>
  );
}
