import type { Metadata } from "next";
// import "./globals.css";
import Footer from "@/components/layout/footer";
// import Navbar from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "GO Spives",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        {/* <Navbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
